version: '3'

services:

  backend:
    image: "${BACKEND_IMAGE}"
    environment:
      - "VIRTUAL_HOST=${BACKEND_VIRTUAL_HOST}"
      - "VIRTUAL_PORT=${BACKEND_VIRTUAL_PORT}"
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_HOST=postgres"
      - "POSTGRES_PORT=5432"
      - "POSTGRES_DB=example"
    depends_on:
      - postgres
    restart: always
      
  frontend:
    image: "${FRONTEND_IMAGE}"
    environment:
      - "VIRTUAL_HOST=${FRONTEND_VIRTUAL_HOST}"

  postgres:
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432  
    volumes:
      - db_volume:/var/lib/postgresql

  reverseproxy:
    image: jwilder/nginx-proxy
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - ./certs:/etc/nginx/certs
    environment:
      - "DEFAULT_HOST=${FRONTEND_VIRTUAL_HOST}"

volumes:
  db_volume:
