version: '3'
services:
  myapp-backend:
    image: "tobiaslocker/simple-dockerized-flask-backend:v0.1"
    environment:
      - "VIRTUAL_HOST=backend.decent.sh"
      - "VIRTUAL_PORT=8080"
    ports:
      - "8080:80"
  myapp-frontend:
    image: "tobiaslocker/simple-dockerized-react-frontend:v0.1"
    environment:
      - "VIRTUAL_HOST=frontend.decent.sh"

  reverseproxy:
    image: jwilder/nginx-proxy
    depends_on:
      - myapp-frontend
      - myapp-backend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
