version: '3'
services:
  myapp-frontend:
    image: "tobiaslocker/simple-dockerized-react-frontend:v0.1"
    environment:
      - "VIRTUAL_HOST=decent.sh"
      - "VIRTUAL_PORT=80"

  reverseproxy:
    image: jwilder/nginx-proxy
    depends_on:
      - myapp-frontend
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
